#!/bin/bash

echo "======================================================================"
echo " M2 Air Optimized Training - Quick Guide"
echo "======================================================================"
echo ""
echo "Optimizations Applied:"
echo "  ✅ M2 GPU (MPS) acceleration"
echo "  ✅ Mixed precision training (faster)"
echo "  ✅ Batch size: 32 (optimized for M2)"
echo "  ✅ Gradient accumulation: 2 (effective batch=64)"
echo "  ✅ Multi-core data loading: 4 workers"
echo ""
echo "Expected Performance:"
echo "  • GPU Usage: 80-95% (during training)"
echo "  • Each epoch: ~3-4 minutes"
echo "  • Total time: 5-7 hours"
echo ""
echo "======================================================================"
echo ""
echo "Commands:"
echo ""
echo "1. Start Full Training:"
echo "   ./start_full_training.sh"
echo ""
echo "2. Monitor GPU while training:"
echo "   # Open Activity Monitor > Window > GPU History"
echo "   # Or use: sudo powermetrics --samplers gpu_power -i 1000"
echo ""
echo "3. Check progress in terminal:"
echo "   # You'll see: Epoch X/100: 100%|████| loss=X.XX"
echo ""
echo "IMPORTANT:"
echo "  - Keep MacBook plugged in (6+ hours)"
echo "  - GPU will be HOT (normal, M2 can handle it)"
echo "  - Don't interrupt training"
echo ""
echo "======================================================================"
